# Generated by Django 5.1.4 on 2025-03-02 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_room_group_id_room_is_group_room_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_group',
        ),
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
    ]
